apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  db: techan_unchained
  user: techan_unchained
  password: techan_unchained
  master-password: master_password
