---
sudo: false
language: python
python:
  - 3.6
install:
  - cp app/config.example.py app/config.py
  - pip install tox-travis
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt  # required for building the docs
script:
  - tox
  - travis-sphinx build --nowarn --source=docs
services:
  - redis-server
after_success:
  - travis-sphinx deploy
