kind: Service
apiVersion: v1
metadata:
  name: marketstore-service
  labels:
    app: marketstore
spec:
  type: ClusterIP
  selector:
    app: marketstore
  ports:
  - name: marketstore
    protocol: TCP
    port: 5993
    targetPort: 5993
