kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: marketstore-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: marketstore-pv
