kind: PersistentVolume
apiVersion: v1
metadata:
  name: marketstore-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /minikube-data/mktsdb
